### ISSUE TITLE
Bug: Red banner expands when navigating away

### ISSUE THREAD

**Issue by missingfaktor** [missingfaktor/missingfaktor.github.io#6]
When you click the red banner, before you reach your next page, it expands for a bit.

The same happens at a specific width of the page.

**Comment by ishantsolanki** [comment]
This is when we have the dev tools on and cache disabled. This forces the page to download the font on each page navigation, and while the font is being downloaded, the default fonts take up more width hence we see an expanded flicker. Try with dev tools off and see if the issue persists

**Comment by missingfaktor** [comment]
Ah I see. Let's close this then.
